world_locations = ['london', 'tokyo', 'new york', 'helsinki', 'madrid']
print(world_locations)
print(sorted(world_locations))
print(world_locations)
print(sorted(world_locations, reverse=True))
print(world_locations)
world_locations.reverse()
print(world_locations)
world_locations.reverse()
print(world_locations)
world_locations.sort()
print(world_locations)
world_locations.sort(reverse=True)
print(world_locations)
